### ISSUE TITLE
Making a Logo

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/exspy#17]
#### Describe the bug
We should make a logo for exspy.

I've just mocked up a simple logo based on a combination of the Rosettasciio logo with the snake and the hyperspy logo. Eventually we can try to make something better but maybe this is a good starting place. 

![exspy2_white](https://github.com/hyperspy/exspy/assets/41125831/b56feed7-2895-4ac8-8725-5949bd742d8b)

**Comment by jlaehne** [comment]
What comes to my mind is something based on a mockup of the inner atomic shells that are important for both EDX/EELS - something like a simplified version of the following?
![exp_edx-scheme](https://github.com/hyperspy/exspy/assets/7076057/e14cd9ee-b7a2-41db-9b07-9b6b1fda5b53)

One could consider using the coloring of the hypercube for the different shells to make an association to the hyperspy logo, maybe also make the shells slightly elliptic/or 3D to get away from a darts board like representation? Like a cut-open ball model with colored shells.

**Comment by CSSFrancis** [comment]
I generally don't like 3D for logos as it's hard to do right. I kind of like making letters too. Maybe we can have the shells and then something like an incoming electron an X-ray scattered off and then a scattered electron making a y?

**Comment by CSSFrancis** [comment]
I tried something, but I don't thing it really worked out as well as I thought I would have :)
![drawing](https://github.com/hyperspy/exspy/assets/41125831/8faf090e-1fb2-453c-aa62-a964f1d8a407)

**Comment by CSSFrancis** [comment]
![exspy3](https://github.com/hyperspy/exspy/assets/41125831/7ef9075f-fe39-4b1d-818e-2eda4c8d3101)

**Comment by CSSFrancis** [comment]
Just mocking somethings up....

![exspy_full](https://github.com/hyperspy/exspy/assets/41125831/2e830d07-ca44-4e58-8c6e-d02346184ab2)

**Comment by jlaehne** [comment]
Played with the ideas a bit further:

![exspy](https://github.com/hyperspy/exspy/assets/7076057/dc17c270-3c4d-4de9-b7a6-b0946ee64bab)

I really like the last version with italics and a small e for electrons and large X for X-rays.

**Comment by jlaehne** [comment]
The last one also in a dark mode version (like for LumiSpy I would propose to have both versions):

![image](https://github.com/hyperspy/exspy/assets/7076057/bb7ec427-e8f5-48ee-a6b2-5bdaa408e223)

**Comment by CSSFrancis** [comment]
@jlaehne I think that looks good! The dark version with a sand serif  font looks better than the options with a serif font.

Maybe things might look a bit better if the font and rings are w a bit thicker but that's just a minor thing to play around with.

All together I like it :) and I think the y looks cool.

**Comment by jlaehne** [comment]
I looked for a font that matches the rounded head lines I used in the y and that is indeed best with Nunito. I made the rings a bit thicker and experimented with a slightly thicker version of the font. However, in the thicker version, the wiggled X-ray line does not look good any more, so I would stick with 'Nunito light it':

![exspy](https://github.com/hyperspy/exspy/assets/7076057/4356af53-24c9-41ff-a7e5-e82586f45cfe)

I used the same font for a holospy logo: https://github.com/hyperspy/holospy/issues/20

**Comment by CSSFrancis** [comment]
@jlaehne sounds good to me! I think I dont have the font installed so the svg didn't render properly. 

You're right that the little thicker line for makes the x ray a little weird.

**Comment by jlaehne** [comment]
Then here comes a png preview to avoid any font issues (the final svg will then have the text converted to a path):
![image](https://github.com/hyperspy/exspy/assets/7076057/dacd9c1e-9cb3-4d7e-b61d-8f4d0df892b1)

As said, I would go for the upper set.

**Comment by ericpre** [comment]
Thank you @jlaehne and @CSSFrancis, this is already quite good. I really liked @jordiferrero's contribution to lumispy and rosettasciio logos, @jordiferrero, would be interested and have time to do some of your magics?

**Comment by jordiferrero** [comment]
I love making logos - this is what I came up after 30min. Any comments?
![image](https://github.com/hyperspy/exspy/assets/9082687/4902451e-a9d4-4dcb-b3cf-04c88bca7920)

**Comment by jordiferrero** [comment]
> Thank you @jlaehne and @CSSFrancis, this is already quite good. I really liked @jordiferrero's contribution to lumispy and rosettasciio logos, @jordiferrero, would be interested and have time to do some of your magics?

I love making logos - this is what I came up after 30min. Any comments?
![image](https://github.com/hyperspy/exspy/assets/9082687/4902451e-a9d4-4dcb-b3cf-04c88bca7920)

**Comment by jlaehne** [comment]
Thanks @jordiferrero for jumping in so quickly. Your wave is definitely better than mine, I realize that I squeezed in too many lobes. I still like the idea though that the scattering occurs on one of the shells, even if it leads to an overlap of lines. Not sure if the arrow heads are necessary (the upper left line would be the incoming electron and the lower left one the outgoing).

Based on your design, I improved on my last proposal (better wave, less strict shape of the y with respect to the one from the font, more pronounced snakehead) and can now even accomodate the slightly thicker font that @CSSFrancis was proposing:

![image](https://github.com/hyperspy/exspy/assets/7076057/60a30a4d-7837-433b-83fe-8725bd9068e9)

**Comment by CSSFrancis** [comment]
@jordiferrero If you want some more logos to play around with there is always https://github.com/pyxem/pyxem/issues/984 https://github.com/pyxem/diffsims/issues/192 and https://github.com/hyperspy/holospy/issues/20 (I'm only kind of kidding)

Although it is nice to have the scattering from some shell of the electron I think I like @jordiferrero's design with the cut away from a aesthetics perspective as it does make things look less busy.  The "y" is kind of lost on me in that design and I don't know the top rays have to be quite that long.  I would just make it a lower case y by moving it down and chopping off part of the incoming electron and outgoing x ray.

**Comment by HanHsuanWu** [comment]
interesting to see how the logos progresses lol. Nice

**Comment by CSSFrancis** [comment]
> interesting to see how the logos progresses lol. Nice

No one ever said that we were quick about these kind of things :)  The Rosettasciio logo thread was fun to follow as well.


In any case how do we feel about something like this? Some one who is better at making logos might have to make it so that 


 PNG
![exspy2](https://github.com/hyperspy/exspy/assets/41125831/ed5aa742-7b19-4283-b575-483c6a101bbd)

SVG
![exspy2](https://github.com/hyperspy/exspy/assets/41125831/cbfa0e6a-cbc6-42ae-9e41-2da8c96f1463)

**Comment by ericpre** [comment]
Thank you @CSSFrancis, @jlaehne and @jordiferrero  for the mockups.
I am not I like the italic font and the elliptic shells. I find one of @CSSFrancis's early version (in https://github.com/hyperspy/exspy/issues/17#issuecomment-1868307005) quite simple and nice - the position of the shells doesn't look right though!

**Comment by jlaehne** [comment]
Based on feedback from @CSSFrancis: y a bit smaller again and lower and lines not overlapping (can still be optimized if we go for it). For @ericpre a non-italic version.

![image](https://github.com/hyperspy/exspy/assets/7076057/50f174e0-1324-46a6-8823-09da9356f0c6)

I like the "elliptic shells" as a kind of tilted view, because I find it plays better with the scattering process being closer to a 'y'.

**Comment by francisco-dlp** [comment]
The logo looks great. Before Christmas  I started thinking on a different approach that involved placing the letters inside squares representing an unfolded tesseract, but styled as a periodic table. I am glad that I didn't try to implement this idea, since I like more the shells logo above.

A small suggestion: what about moving the head of the snake to the wobbly line?

**Comment by ericpre** [comment]
Thank you @jlaehne, the shells are looking good. I still feel that that there are some proportions that are not quite right: maybe increase the "thickness" of the font (something similar to the lumispy and rosettasciio logos?) and align the `Y` to be lower case (at the moment, it seems to be in-between lower and upper case).

The snake on the `S` seems to have become a pattern, first introduced in the lumispy logo and then used in the rosettasciio logo! ;) It would be nice to keep this pattern.

**Comment by jlaehne** [comment]
The `y` was more like the lower case one in https://github.com/hyperspy/exspy/issues/17#issuecomment-1872211560
Then from https://github.com/hyperspy/exspy/issues/17#issuecomment-1874264870 I thought that for a logo I should maybe not be so strict on that.

I already pushed the font thickness, but with more the `y` will start looking odd, in particular the x-ray photon wave.

I can slightly optimize the shape of the `y`, the cutout of the shells and the snakehead, but before I spent time on that would like to decide between the following options, so lets have a vote!

- :rocket: nunito italics
- :tada: nunito upright
- :+1: intermediate `y` as in https://github.com/hyperspy/exspy/issues/17#issuecomment-1883818286
- :-1: lowered `y` more like in https://github.com/hyperspy/exspy/issues/17#issuecomment-1872211560

**Comment by jlaehne** [comment]
We need more opinions in the poll here @CSSFrancis @hakonanes @francisco-dlp @jordiferrero @HanHsuanWu

**Comment by hakonanes** [comment]
Voted. Great work, I think the logo perfectly captures the relevant spectroscopies. I like the colors, too!

**Comment by jlaehne** [comment]
OK, I'm outvoted. Here is the result:

![image](https://github.com/hyperspy/exspy/assets/7076057/b5b95f65-1e98-4229-bb0e-e1f0bfec7f70)
