### ISSUE TITLE
Can not download the GOSH file

### ISSUE THREAD

**Issue by PhysXu** [hyperspy/exspy#47]
#### Describe the bug
when I try the "fine structure" fitting in HyperSpy, I was stuck by the following error:
![image](https://github.com/hyperspy/exspy/assets/35793078/d3605b8f-f091-4e4c-8096-bc6b2817f5eb)

#### Python environement:
 - eXSpy version: 0.1
 - HyperSpy version: 2.0
 - Python version: 3.x

**Comment by ericpre** [comment]
I have tried the following (same as the example given in https://hyperspy.org/exspy/user_guide/eels.html#generalised-oscillator-strengths) and it works fine

```python
import pooch
GOSH10 = pooch.retrieve(
    url="doi:10.5281/zenodo.6599071/Segger_Guzzinati_Kohl_1.0.0.gos",
    known_hash="md5:d65d5c23142532fde0a80e160ab51574",
)
```

Have you tried to run this several times, in case this is a transcient issue with the internet connection or zenodo?

Note that this is an example to show how to download another GOS than the default one, if you are happy with the default version of this GOS, you don't need to do that step.
