### ISSUE TITLE
Unable to add elements to signals

### ISSUE THREAD

**Issue by robhooley** [hyperspy/exspy#98]
#### Describe the bug
Unable to add elements to signals

Minimum working example of code

![image](https://github.com/user-attachments/assets/c6d07f80-51a0-4b95-933a-94ce957325cc)

![image](https://github.com/user-attachments/assets/b861868d-b06f-402a-ab8d-5c6c6ae4c671)

#### Expected behavior
signal.add_elements should add the elements, as it is written in your documentation

#### Python environement:
 - eXSpy version: 0.3.1
 - HyperSpy version: 2.2.0
 - Python version: 3.12.7

![image](https://github.com/user-attachments/assets/c6d07f80-51a0-4b95-933a-94ce957325cc)

I'm going to be completely honest, the documentation here after the split from Hyperspy to Exspy and Rosetta is outdated and does not match the real code, it is useless. It has become incredibly frustrating to use these packages after the split, even your own examples do not work, how do you expect people to pick these packages up as they have become needlessly more complex.

**Comment by robhooley** [comment]
I have this now and it seems to be working after restarting the Jupyterlab instance:
![image](https://github.com/user-attachments/assets/bde7aa33-01b5-4e57-9234-1eb470e19bad)

However yesterday when I had this problem, the import statements were the same but this was shown instead:
![image](https://github.com/user-attachments/assets/73f70bac-b03b-4b0c-9e7d-a488c03c6719)

**Comment by ericpre** [comment]
@robhooley, what you are describing is consistent with an installation issue / using the incorrect python environment in [your first message](https://github.com/hyperspy/exspy/issues/98#issue-2691442748).
If you want something that works out of the box, you can use the hyperspy bunble: https://hyperspy.org/hyperspy-bundle and the corresponding shortcuts/instructions to initialise the correct python environment (in case multiple python environment are installed).
Unfortunately, considering the way python distribution works, it is relatively easy to break python distribution and this is the motivation for providing the hyperspy bundle.

**Comment by jlaehne** [comment]
Closing as this seems to be resolved.
